Add notebooks for first-hit analysis on aggregated levels and scripts for single-cell analysis.
Arkkienkeli/DeepProfilerExperiments pull request #7
Opened 2022-06-21 10:47 UTC by Arkkienkeli

For single-cells, in case of TA-ORF there is a notebook, for BBBC022 a script (to run it in tmux as it takes time to run).

2022-06-23 21:17 UTC, jccaicedo requested changes

2022-06-23 21:17 UTC, jccaicedo commented on bbbc022/first-hits-single-cell.py
> +def request_controls(control_meta_subset):
Move function up before the executable code starts (before line 80).

2022-06-23 21:17 UTC, jccaicedo commented on bbbc022/first-hits-single-cell.py
> +def request_treatments(treatments_meta_subset):
Same here, move function up.

2022-06-23 21:17 UTC, jccaicedo commented on bbbc022/first-hits-single-cell.py
> +for i in range(10):
Bring all the main code to this block and wrap it in the following conditional:
```
if __name__ == "__main__":
    # Executable code here
```
See why here: https://stackoverflow.com/questions/419163/what-does-if-name-main-do

2022-06-23 21:17 UTC, jccaicedo commented on bbbc022/first-hits-single-cell.py
> +        s = time.time()
Can be removed

2022-06-23 21:17 UTC, jccaicedo commented on bbbc022/first-hits-single-cell.py
> +import time
Can be removed (unused in the logic)

2022-06-23 21:17 UTC, jccaicedo commented on bbbc022/first-hits-aggregated.ipynb
> +    "def find_first_hits(features, feats, pert_name, control):\n",
Is this function different for aggregated profiles and for single cells?
In principle, they are the same. We need to unify them and have only one implementation. Let's refactor and move these functions out to a module called `first_hits.py` in the `profiling` directory. In that way, we can reuse it in all other scripts.

2022-06-23 21:17 UTC, jccaicedo commented on bbbc022/first-hits-aggregated.ipynb
> +    "def summarize(results):\n",
Try to refactor and keep in a separate module that can be imported.

2022-06-23 21:20 UTC, jccaicedo commented
The logic seems to be OK overall, but the scripts have redundant code. Let's make an effort to factorize and reuse code as much as we can across all scripts (especially functions). Ideally, each script in this PR should have logic that is specific to the dataset only.

2024-01-02 10:26 UTC, Arkkienkeli commented
We eventually did not use this analysis in the final publication, thus we are not going to merge this code.

2024-01-02 10:26 UTC, closed without merging